# Generated by Django 6.0.6 on 2026-06-04 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('libelle', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.PositiveSmallIntegerField(default=40)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Salle',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')])),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='eleves.classe')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='enseignants.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='enseignants.matiere')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='emploi_du_temps.creneauhoraire')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='emploi_du_temps.salle')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['jour', 'creneau__heure_debut'],
                'unique_together': {('classe', 'jour', 'creneau')},
            },
        ),
    ]
