# Generated by Django 6.0.5 on 2026-06-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_ecole_alter_classe_options_niveau_code_niveau_cycle_and_more'),
        ('emploi_du_temps', '0001_initial'),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_heures_semaine', models.PositiveSmallIntegerField(default=2, verbose_name='Heures/semaine')),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_matieres', to='eleves.classe')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classe_matieres', to='enseignants.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_matieres', to='enseignants.matiere')),
            ],
            options={
                'verbose_name': 'Matière par classe',
                'verbose_name_plural': 'Matières par classe',
                'ordering': ['matiere__nom'],
                'unique_together': {('classe', 'matiere')},
            },
        ),
    ]
