# Generated by Django 6.0.5 on 2026-06-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_du_temps', '0002_classematiere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClasseMatiere',
        ),
    ]
