# Generated by Django 6.0.5 on 2026-06-04 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('directeur', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('type_ecole', models.CharField(choices=[('maternelle', 'Maternelle'), ('primaire', 'Primaire'), ('mixte', 'Maternelle + Primaire')], default='mixte', max_length=20)),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['ecole', 'niveau__ordre', 'nom'], 'verbose_name': 'Classe'},
        ),
        migrations.AddField(
            model_name='niveau',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='niveau',
            name='cycle',
            field=models.CharField(choices=[('maternelle', 'Maternelle'), ('primaire', 'Primaire')], default='primaire', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classe',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='eleves.ecole'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'ecole', 'annee_scolaire')},
        ),
    ]
