# Generated by Django 6.0.5 on 2026-06-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_userprofile'),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='enseignant_principal',
            field=models.ForeignKey(blank=True, help_text='Maternelle/Primaire : enseignant qui enseigne toutes les matières', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to='enseignants.enseignant', verbose_name='Enseignant principal'),
        ),
    ]
