# Generated by Django 6.0.5 on 2026-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0005_classe_enseignant_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('transfere', 'Transféré')], db_index=True, default='actif', max_length=20),
        ),
    ]
