# Generated by Django 6.0.5 on 2026-06-18 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0006_alter_eleve_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnexionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_tente', models.CharField(blank=True, max_length=150)),
                ('type_event', models.CharField(choices=[('connexion', 'Connexion réussie'), ('deconnexion', 'Déconnexion'), ('echec', 'Tentative échouée')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connexion_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de connexion',
                'verbose_name_plural': 'Journal des connexions',
                'ordering': ['-date'],
            },
        ),
    ]
