# Generated by Django 5.2.16 on 2026-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0007_connexionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='connexionlog',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='connexionlog',
            name='type_event',
            field=models.CharField(choices=[('connexion', 'Connexion réussie'), ('deconnexion', 'Déconnexion'), ('echec', 'Tentative échouée'), ('consultation', 'Consultation'), ('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20),
        ),
    ]
