# Generated by Django 5.2.16 on 2026-08-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0008_connexionlog_path_alter_connexionlog_type_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupescolaire',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Support technique — Email'),
        ),
        migrations.AddField(
            model_name='groupescolaire',
            name='support_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Support technique — Nom'),
        ),
        migrations.AddField(
            model_name='groupescolaire',
            name='support_telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Support technique — Téléphone'),
        ),
    ]
