# Generated by Django 5.2.16 on 2026-08-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0009_groupescolaire_support_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupescolaire',
            name='support_telephone',
            field=models.CharField(blank=True, max_length=60, verbose_name='Support technique — Téléphone'),
        ),
    ]
