# Generated by Django 5.2.16 on 2026-08-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0010_alter_groupescolaire_support_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupescolaire',
            name='support_whatsapp',
            field=models.CharField(blank=True, max_length=30, verbose_name='Support technique — WhatsApp'),
        ),
    ]
