# Generated by Django 6.0.5 on 2026-06-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheancePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_echeance', models.DateField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='paiements.facture')),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echeance', to='paiements.paiement')),
            ],
            options={
                'verbose_name': 'Échéance',
                'ordering': ['numero'],
                'unique_together': {('facture', 'numero')},
            },
        ),
    ]
