# Generated by Django 6.0.5 on 2026-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_echeancepaiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('partiel', 'Partiel'), ('paye', 'Payé'), ('annule', 'Annulé')], db_index=True, default='en_attente', max_length=20),
        ),
    ]
