# Generated by Django 6.0.5 on 2026-06-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0006_alter_eleve_statut'),
        ('paiements', '0003_alter_facture_statut'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together={('eleve', 'type_frais', 'annee_scolaire')},
        ),
    ]
