# Generated by Django 6.0.6 on 2026-06-04 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('emploi_du_temps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeuilleDAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fait', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feuilles_appel', to='emploi_du_temps.cours')),
            ],
            options={
                'verbose_name': "Feuille d'appel",
                'verbose_name_plural': "Feuilles d'appel",
                'ordering': ['-date'],
                'unique_together': {('cours', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'En retard'), ('excuse', 'Absent excusé')], default='present', max_length=20)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='presences/justificatifs/')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='emploi_du_temps.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date'],
                'unique_together': {('eleve', 'cours', 'date')},
            },
        ),
    ]
