# Generated by Django 6.0.5 on 2026-06-16 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_du_temps', '0002_classematiere'),
        ('presences', '0002_alter_presence_date_alter_presence_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuilledappel',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feuilles_appel', to='emploi_du_temps.cours'),
        ),
    ]
