# Generated by Django 6.0.6 on 2026-06-04 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('type_evaluation', models.CharField(choices=[('devoir', 'Devoir'), ('composition', 'Composition'), ('interrogation', 'Interrogation'), ('examen', 'Examen')], max_length=20)),
                ('periode', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3'), ('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=5)),
                ('date', models.DateField()),
                ('note_max', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='eleves.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='eleves.classe')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='enseignants.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='enseignants.matiere')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3'), ('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=5)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rang', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('appreciation', models.TextField(blank=True)),
                ('date_generation', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='eleves.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'ordering': ['-annee_scolaire__date_debut', 'periode'],
                'unique_together': {('eleve', 'annee_scolaire', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('absent', models.BooleanField(default=False)),
                ('observation', models.CharField(blank=True, max_length=200)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.eleve')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.evaluation')),
            ],
            options={
                'verbose_name': 'Note',
                'ordering': ['eleve__nom'],
                'unique_together': {('eleve', 'evaluation')},
            },
        ),
    ]
